appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
bot: {automerge: true}
conda_forge_output_validation: true
provider: {linux_aarch64: default, linux_ppc64le: default, win: azure}
travis:
  secure: {BINSTAR_TOKEN: BemLdvCGMrz1uWk0DbcvS1B9K3VQUXdQkJka+u/UjOZvAOD3T7dzW+gu7V2tYdTZwI0qch7az/nfHaWCcIoBgwX2jayrdehJMz5712POQK8qA68h8tX7djG6uhJ79wQAVVlfIFUMoPjyM4jVyJ3v7FSZK9lYLq8OEFKcNhETPjbXiVfwrJsXP6eKNu1qm4ntmJ1eJdzd+Qik40uD1KEaDsRiDqYbRYyRBHmpekGQswkZGnobrgwdMeYB9C+7kTavoGwJzIooR8cb7hBQR3405BNaGXEvfaFxUhTF42bzFPRisJjK9JAaPa0rPp3mhJ5Y9/b5rz9xYCVIPwgWz+TlPLoddAh80Me6tim/KL9dJ9sw3aIi+Qwxm+gw5uENv2xhmfSLtmYQyu0Z9AN8rcZqTAmu53EAu2bAS1bTS231+pF7+6LAlmv18y/mW4v7bxlk8R+vpfb/egtMmgZz8G/eg16gAkVc+yGGO6iOQjpmii8HAq1GxbbZcss1w7gbrJtg8OH1czbNYzjWPhr9ai1+5K8ORm2BJOtxDHen7YxNVQnEgPkuojg8HNncH4z7lwCLwJqM0IotTdEP754C8B0aHL91PxL+4oM5ZmyKDPZINJ00J2MMNKHMpGC1tih5AW5BmojXLv9JWHKgwNvNXtobl0r4v+O2kDHbw2Rp4Wb1ykw=}
